In [1]:
import pandas as pd
import numpy as np

# A. 데이터 전처리

In [144]:
# 데이터 추출
trn = pd.read_csv('./train_ver2.csv')
trn

C:\Users\SMART09\AppData\Local\Temp\ipykernel_3524\1972658950.py:2: DtypeWarning: Columns (5,8,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  trn = pd.read_csv('./train_ver2.csv')


fecha_dato  ncodpers ind_empleado pais_residencia sexo  age  \
0         2015-01-28   1375586            N              ES    H   35   
1         2015-01-28   1050611            N              ES    V   23   
2         2015-01-28   1050612            N              ES    V   23   
3         2015-01-28   1050613            N              ES    H   22   
4         2015-01-28   1050614            N              ES    V   23   
...              ...       ...          ...             ...  ...  ...   
13647304  2016-05-28   1166765            N              ES    V   22   
13647305  2016-05-28   1166764            N              ES    V   23   
13647306  2016-05-28   1166763            N              ES    H   47   
13647307  2016-05-28   1166789            N              ES    H   22   
13647308  2016-05-28   1550586            N              ES    H   37   

          fecha_alta  ind_nuevo antiguedad  indrel ult_fec_cli_1t indrel_1mes  \
0         2015-01-12        0.0          6     1.0            NaN         1.0   
1         2012-08-10        0.0         35     1.0            NaN         1.0   
2         2012-08-10        0.0         35     1.0            NaN         1.0   
3         2012-08-10        0.0         35     1.0            NaN         1.0   
4         2012-08-10        0.0         35     1.0            NaN         1.0   
...              ...        ...        ...     ...            ...         ...   
13647304  2013-08-14        0.0         33     1.0            NaN           1   
13647305  2013-08-14        0.0         33     1.0            NaN           1   
13647306  2013-08-14        0.0         33     1.0            NaN           1   
13647307  2013-08-14        0.0         33     1.0            NaN         1.0   
13647308  2016-05-13        1.0          0     1.0            NaN         NaN   

         tiprel_1mes indresi indext conyuemp canal_entrada indfall  tipodom  \
0                  A       S      N      NaN           KHL       N      1.0   
1                  I       S      S      NaN           KHE       N      1.0   
2                  I       S      N      NaN           KHE       N      1.0   
3                  I       S      N      NaN           KHD       N      1.0   
4                  A       S      N      NaN           KHE       N      1.0   
...              ...     ...    ...      ...           ...     ...      ...   
13647304           I       S      N      NaN           KHE       N      1.0   
13647305           I       S      N      NaN           KHE       N      1.0   
13647306           A       S      N      NaN           KHE       N      1.0   
13647307           I       S      N      NaN           KHE       N      1.0   
13647308         NaN       S      N      NaN           NaN       N      1.0   

          cod_prov      nomprov  ind_actividad_cliente      renta  \
0             29.0       MALAGA                    1.0   87218.10   
1             13.0  CIUDAD REAL                    0.0   35548.74   
2             13.0  CIUDAD REAL                    0.0  122179.11   
3             50.0     ZARAGOZA                    0.0  119775.54   
4             50.0     ZARAGOZA                    1.0        NaN   
...            ...          ...                    ...        ...   
13647304      50.0     ZARAGOZA                    0.0   43912.17   
13647305      26.0    RIOJA, LA                    0.0   23334.99   
13647306      50.0     ZARAGOZA                    1.0        NaN   
13647307      50.0     ZARAGOZA                    0.0  199592.82   
13647308      28.0       MADRID                    1.0        NaN   

                    segmento  ind_ahor_fin_ult1  ind_aval_fin_ult1  \
0          02 - PARTICULARES                  0                  0   
1         03 - UNIVERSITARIO                  0                  0   
2         03 - UNIVERSITARIO                  0                  0   
3         03 - UNIVERSITARIO                  0                  0   
4         03 - UNIVERSITARIO    

In [94]:
pd.set_option('display.max_columns', None)  # 열의 수 제한 해제
pd.set_option('display.width', None)  # 출력 너비 제한 해제

In [97]:
# len(trn) #1364만개

In [98]:
# trn.info()

In [99]:
#성별

In [100]:
trn.sexo.info()

<class 'pandas.core.series.Series'>
RangeIndex: 13647309 entries, 0 to 13647308
Series name: sexo
Non-Null Count     Dtype 
--------------     ----- 
13619505 non-null  object
dtypes: object(1)
memory usage: 104.1+ MB


In [101]:
# 결측치 제거
refined_trn = trn.loc[ (trn.sexo.notnull() ) ]
# refined_trn
refined_trn.sexo = np.where( refined_trn.sexo=='H', "1", "0")

C:\Users\SMART09\AppData\Local\Temp\ipykernel_3524\345525901.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  refined_trn.sexo = np.where( refined_trn.sexo=='H', "1", "0")


In [102]:
# 성별 컬럼 전처리 결과 확인
refined_trn.sexo.unique()

array(['1', '0'], dtype=object)

In [104]:
# 월 초 고객 유형

In [105]:
refined_trn.indrel_1mes.info()

<class 'pandas.core.series.Series'>
Int64Index: 13619505 entries, 0 to 13647308
Series name: indrel_1mes
Non-Null Count     Dtype 
--------------     ----- 
13497458 non-null  object
dtypes: object(1)
memory usage: 207.8+ MB


In [106]:
refined_trn.indrel_1mes.unique()

array([1.0, 3.0, 2.0, nan, '1.0', '1', '3', '3.0', '2.0', '4.0', 'P', '4',
       4.0, '2'], dtype=object)

In [107]:
# 결측치 제거
refined_trn = refined_trn.loc[ (refined_trn.indrel_1mes.notnull() ) ]

# 1. int형변환 2. p->5 
try:
    refined_trn.loc[refined_trn.indrel_1mes.str.upper()=="P", "indrel_1mes"] = 5
except Exception as e:
    print(e)

In [108]:
refined_trn.indrel_1mes.unique()

array([1.0, 3.0, 2.0, '1.0', '1', '3', '3.0', '2.0', '4.0', 5, '4', 4.0,
       '2'], dtype=object)

In [109]:
try:
    refined_trn.indrel_1mes = refined_trn.indrel_1mes.astype(float)
    refined_trn.indrel_1mes = refined_trn.indrel_1mes.astype(int)
except Exception as e:
    print(e)

In [110]:
# '월 초 고객 유형' 컬럼 전처리 결과 확인
refined_trn.indrel_1mes.unique()

array([1, 3, 2, 4, 5])

In [111]:
# 월 초 고객 관계 유형

In [112]:
refined_trn.tiprel_1mes

0           A
1           I
2           I
3           I
4           A
           ..
13647303    I
13647304    I
13647305    I
13647306    A
13647307    I
Name: tiprel_1mes, Length: 13497458, dtype: object

In [113]:
refined_trn.tiprel_1mes.unique()

array(['A', 'I', 'P', 'R', 'N'], dtype=object)

In [114]:
refined_trn.tiprel_1mes.isnull().sum()

0

In [115]:
dict = {"I":0, "A":1, "P":2,"R":3, "N":4}

In [116]:
refined_trn.tiprel_1mes = refined_trn.tiprel_1mes.str.upper()
refined_trn.tiprel_1mes = refined_trn.tiprel_1mes.map(dict)

In [117]:
# 월 초 고객 관계 유형 전처리 결과 확인
refined_trn.tiprel_1mes.unique()

array([1, 0, 2, 3, 4], dtype=int64)

In [118]:
# 거주지 지수

In [119]:
refined_trn.indresi.isnull().sum()

0

In [120]:
refined_trn.indresi.unique()

array(['S', 'N'], dtype=object)

In [121]:
dict = {"N":0, "S":1}

refined_trn.indresi = refined_trn.indresi.str.upper()
refined_trn.indresi = refined_trn.indresi.map(dict)

In [122]:
# 결과 확인
refined_trn.indresi.unique()

array([1, 0], dtype=int64)

In [123]:
# 외국인 지수

In [124]:
refined_trn.indext.isnull().sum()

0

In [125]:
refined_trn.indext.unique()

array(['N', 'S'], dtype=object)

In [126]:
dict = {"N":0, "S":1}

refined_trn.indext = refined_trn.indext.str.upper()
refined_trn.indext = refined_trn.indext.map(dict)

In [127]:
# 결과 확인
refined_trn.indext.unique()

array([0, 1], dtype=int64)

In [128]:
# 고객분류 

In [129]:
refined_trn.segmento.isnull().sum()

39653

In [130]:
refined_trn.segmento.unique()

array(['02 - PARTICULARES', '03 - UNIVERSITARIO', '01 - TOP', nan],
      dtype=object)

In [131]:
refined_trn = refined_trn.loc[refined_trn.segmento.notnull()]

In [132]:
refined_trn.segmento.isnull().sum()

0

In [140]:
refined_trn.segmento = np.where( refined_trn.segmento == '03 - UNIVERSITARIO', 0, 
                                np.where( refined_trn.segmento == '01 - TOP', 1,
                                          np.where( refined_trn.segmento == '02 - PARTICULARES', 1, refined_trn.segmento) ) )

In [93]:
# dict = {'03 - UNIVERSITARIO':0, '01 - TOP':1, '02 - PARTICULARES':1}

# refined_trn.segmento = refined_trn.segmento.str.upper()
# refined_trn.segmento = refined_trn.segmento.map(dict)

# refined_trn.segmento.unique()

# refined_trn.segmento.head(20)

In [142]:
# 결과 확인
refined_trn.segmento.unique()

array([1, 0], dtype=object)